policies:
    - type: commit
      spec:
          header:
              length: 89
              imperative: true
              case: lower
              invalidLastCharacters: .
          body:
              required: false
          dco: false
          spellcheck:
              locale: US
          maximumOfOneCommit: false
          conventional:
              scopes:
                  - master
                  - deps
              types:
                  - feat
                  - fix
                  - chore
                  - deps
                  - docs
                  - ci
