---
include:
  - Rakefile
  - Gemfile
  - "*.gemspec"
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - standardrb
  - require_not_found
formatter:
  - standardrb
require_paths: []
plugins:
  - solargraph-standardrb
max_files: 5000
