# frozen_string_literal: true

require "polars-df"
require "networkx"
require "zip"
require_relative "gtfs_df/base_gtfs_table"
require_relative "gtfs_df/utils"
require_relative "gtfs_df/version"
require_relative "gtfs_df/schema/enum_values"
require_relative "gtfs_df/schema/agency"
require_relative "gtfs_df/schema/calendar"
require_relative "gtfs_df/schema/calendar_dates"
require_relative "gtfs_df/feed"
require_relative "gtfs_df/graph"
require_relative "gtfs_df/reader"
require_relative "gtfs_df/schema/routes"
require_relative "gtfs_df/schema_validator"
require_relative "gtfs_df/schema/stop_times"
require_relative "gtfs_df/schema/stops"
require_relative "gtfs_df/schema/trips"
require_relative "gtfs_df/schema/pathways"
require_relative "gtfs_df/schema/levels"
require_relative "gtfs_df/schema/feed_info"
require_relative "gtfs_df/schema/shapes"
require_relative "gtfs_df/schema/frequencies"
require_relative "gtfs_df/schema/transfers"
require_relative "gtfs_df/schema/fare_attributes"
require_relative "gtfs_df/schema/fare_rules"
require_relative "gtfs_df/schema/attributions"
require_relative "gtfs_df/schema/translations"
require_relative "gtfs_df/schema/stop_areas"
require_relative "gtfs_df/schema/stop_attributes"
require_relative "gtfs_df/schema/rider_categories"
require_relative "gtfs_df/schema/fare_media"
require_relative "gtfs_df/schema/fare_products"
require_relative "gtfs_df/schema/fare_leg_rules"
require_relative "gtfs_df/schema/fare_leg_join_rules"
require_relative "gtfs_df/schema/fare_transfer_rules"
require_relative "gtfs_df/schema/areas"
require_relative "gtfs_df/schema/networks"
require_relative "gtfs_df/schema/route_networks"
require_relative "gtfs_df/schema/location_groups"
require_relative "gtfs_df/schema/location_group_stops"
require_relative "gtfs_df/schema/booking_rules"
require_relative "gtfs_df/writer"

module GtfsDf
  class Error < StandardError; end
end
